[project]
name = "temporal-r2-ocr-workflow"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10.16"
dependencies = [
    "anthropic>=0.49.0",
    "boto3>=1.37.18",
]
